# Generated by Django 3.1.4 on 2021-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210509_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
